### ISSUE TITLE
Check and possibly switch to using K8s annotations to discover engines

### ISSUE THREAD

**Issue by janmiderback** [qlik-oss/mira#264]
Currently, Mira uses labels on engines in K8s for discovery.
It might be more suitable to use annotations (like e.g. Prometheus).
Check if so, and make the required implementation.

**NOTE**
Large impact. Likely we need to keep label support and later deprecate it.

**Comment by FredrikFolkesson** [comment]
Why should we do this switch? We are using labels in the correct way (small information and to use when querying to the kubernetes api)

> You can use either labels or annotations to attach metadata to Kubernetes objects. Labels can be used to select objects and to find collections of objects that satisfy certain conditions. In contrast, annotations are not used to identify and select objects.

**Comment by janmiderback** [comment]
I think we should consult sources outside our team in order to make the right decision. The Qlik engine team is the team most affected by this (the engine being the pod sitting around with these labels or annotations) so I think we should talk to them first and hear their motifs for either solution. Customers might have opinions too, but it might be too early to have that feedback.

**Comment by janmiderback** [comment]
We will stick to labels since we cannot see any strong reasons to switch. Closing.
Re-open this issue if this is something we should look into again.
