### ISSUE TITLE
Add support for discovery of engines in K8s namespaces

### ISSUE THREAD

**Issue by janmiderback** [qlik-oss/mira#265]
Currently, Mira does not support restricting engine discovery to a single namespace or a selected number of namespaces. This might be very useful if hosting many separate deployments in the same K8s cluster, where one instance of Mira should only operate in a certain namespace.

Investigate, and identify additional issues as needed.

**Comment by FredrikFolkesson** [comment]
I am closing this as this is not currently in the plans, if you or someone else thinks that this should be implemented please reopen this issue.
