### ISSUE TITLE
Expose /health and /metrics as un-versioned endpoints

### ISSUE THREAD

**Issue by janmiderback** [qlik-oss/mira#275]
It is expected that services expose the `/health` and `/metrics` endpoints without having to specify the API version as in `/v1/metrics` and `/v1/health`.

We should decide if we want to keep `/v1/metrics` and `/v1/health` and if the "un-versioned" endpoints `/health` and `/metrics` shall always point to the latest version, if we get multiple versions of these endpoints.

**Comment by FredrikFolkesson** [comment]
closed with #285
