### ISSUE TITLE
Use mira helm chart in integration tests

### ISSUE THREAD

**Issue by wennmo** [qlik-oss/mira#423]
Currently we are only verifying the helm chart in `/examples`. The integration tests for kubernetes should use the real mira helm chart and the tests should be a prerequisite for publishing a new helm chart to jfrog.

**Comment by wennmo** [comment]
We should also investigate if the Circle CI build should fail or just warn when a new helm chart version is needed. Currently it fails, but perhaps we want to be able to make changes to the helm chart without releasing it.

**Comment by FredrikFolkesson** [comment]
closed with #424
