### ISSUE TITLE
Investigate why helm version > v2.16.3 fails to install chart

### ISSUE THREAD

**Issue by wennmo** [qlik-oss/mira#556]
In Circle CI the `kubernetes` picks up the latest helm version and installs the `mira` chart. This started failing for version `v2.16.5`. The version will be temporarily be pinned to `v2.16.3` but also need to investigate why later releases are failing.

**Comment by sublibra** [comment]
_As of 1 July 2020, Qlik Core is no longer available to new customers. No further maintenance will be done in this repository._
